server:
  port: 8080

spring:
  application:
    name: server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cch?serverTimezone=UTC
    username: root
    password: 2018
#    url: jdbc:mysql://43.136.55.194:3306/cchf?serverTimezone=UTC
#    username: 502scanf
#    password: 2018
  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  # 邮件配置
  mail:
    host: smtp.qq.com                    # QQ邮箱SMTP服务器
    port: 587                            # 端口
    username: 8          # 发件人邮箱（需要替换为你的QQ邮箱）
    password: j
    # 授权码（需要替换为QQ邮箱授权码，不是邮箱密码）
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  mapper-locations:  classpath:mapper/*.xml
  type-aliases-package: cchf.back.entity
  configuration:
    map-underscore-to-camel-case: true
cchf:
  jwt:
    user-secret-key: cocreatehub
    user-ttl: 7200000
    user-token: cch
    room-secret-key: cocreatehubroom
    room-ttl: 3600000
    room-token: cchr
